### ISSUE TITLE
Inventory Item Detail Page

### ISSUE THREAD

**Issue by Jlsmith10** [ucsdCSE110wi16/CSE110M260T15#14]
- [x] Create UI for creating new item
- [x] Change UI for viewing item

**Comment by 0xTenable** [comment]
Inventory Item UI has the requested functionality -- please take a look at branch bug-28 and see if the UI needs any improvements or changes and merge into develop when reviewed!

https://github.com/ucsdCSE110wi16/CSE110M260T15/commits/bug-28
