### ISSUE TITLE
Espresso Testing

### ISSUE THREAD

**Issue by 0xTenable** [ucsdCSE110wi16/CSE110M260T15#19]
Make tests for scenarios in the app.
Test list: 

From start to finish on an account with an apartment:
- [ ] Given that the app is open, when user enters credentials, then user logs in
- [ ] When the user is logged in and uses the side menu to navigate to the my apartment fragment, then the my apartment fragment opens with relevant info. 
- [ ] When the user presses the apartment inventory menu button, then user can see apt. inventory 
- [ ] When user presses the logout button, then user sees the login screen

New User start to finish: 
- [x] Given that user is on login page, when user presses new user signup, then new user can enter his info. 
- [x] When user enters info and presses register, then user can see the main fragment
- [x] When the user goes to apt. page, user can create or join an apartment

**Comment by isaacd9** [comment]
I'd like to work on this, if possible :)
